import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/navbar";
import Footer from "./components/footer"; 

const aeonikPro = localFont({
  src: [
    {
      path: "../fonts/AeonikPro-Black.otf",
      weight: "600",
      style: "black",
    },
    {
      path: "../fonts/AeonikPro-Bold.otf",
      weight: "500",
      style: "bold",
    },
    {
      path: "../fonts/AeonikPro-Medium.otf",
      weight: "400",
      style: "medium",
    },
    {
      path: "../fonts/AeonikPro-Regular.otf",
      weight: "300",
      style: "regular",
    },
    {
      path: "../fonts/AeonikPro-Light.otf",
      weight: "200",
      style: "light",
    },
    {
      path: "../fonts/AeonikPro-Thin.otf",
      weight: "100",
      style: "thin",
    },
  ],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aeonikPro.className}>
        <Nav />
        {children}
        <Footer/>
        </body>
     
    </html>
  );
}
