import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({ src: "./fonts/fonts/GTFlexa-Black.otf" });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
